/** Mirrors `astro_codegen/src/printer/whitespace.rs` — the compiler never collapses these. */
export const rawTextElements = new Set([
	'pre',
	'listing',
	'iframe',
	'noembed',
	'noframes',
	'math',
	'plaintext',
	'script',
	'style',
	'textarea',
	'title',
	'xmp',
]);

// https://github.com/prettier/prettier/blob/main/vendors/html-void-elements.json
export const voidElements = new Set([
	'area',
	'base',
	'basefont',
	'bgsound',
	'br',
	'col',
	'command',
	'embed',
	'frame',
	'hr',
	'image',
	'img',
	'input',
	'isindex',
	'keygen',
	'link',
	'menuitem',
	'meta',
	'nextid',
	'param',
	'source',
	'track',
	'wbr',
]);

/** Extracted verbatim from `prettier/plugins/html.js` so the two printers cannot drift apart. */
const cssDisplay: Record<string, string> = {
	area: 'none',
	base: 'none',
	basefont: 'none',
	datalist: 'none',
	head: 'none',
	link: 'none',
	meta: 'none',
	noembed: 'none',
	noframes: 'none',
	param: 'block',
	rp: 'none',
	script: 'block',
	style: 'none',
	template: 'inline',
	title: 'none',
	html: 'block',
	body: 'block',
	address: 'block',
	blockquote: 'block',
	center: 'block',
	dialog: 'block',
	div: 'block',
	figure: 'block',
	figcaption: 'block',
	footer: 'block',
	form: 'block',
	header: 'block',
	hr: 'block',
	legend: 'block',
	listing: 'block',
	main: 'block',
	p: 'block',
	plaintext: 'block',
	pre: 'block',
	search: 'block',
	xmp: 'block',
	slot: 'contents',
	ruby: 'ruby',
	rt: 'ruby-text',
	article: 'block',
	aside: 'block',
	h1: 'block',
	h2: 'block',
	h3: 'block',
	h4: 'block',
	h5: 'block',
	h6: 'block',
	hgroup: 'block',
	nav: 'block',
	section: 'block',
	dir: 'block',
	dd: 'block',
	dl: 'block',
	dt: 'block',
	menu: 'block',
	ol: 'block',
	ul: 'block',
	li: 'list-item',
	table: 'table',
	caption: 'table-caption',
	colgroup: 'table-column-group',
	col: 'table-column',
	thead: 'table-header-group',
	tbody: 'table-row-group',
	tfoot: 'table-footer-group',
	tr: 'table-row',
	td: 'table-cell',
	th: 'table-cell',
	input: 'inline-block',
	button: 'inline-block',
	fieldset: 'block',
	details: 'block',
	summary: 'block',
	marquee: 'inline-block',
	source: 'block',
	track: 'block',
	meter: 'inline-block',
	progress: 'inline-block',
	object: 'inline-block',
	video: 'inline-block',
	audio: 'inline-block',
	select: 'inline-block',
	option: 'block',
	optgroup: 'block',
};

const inlineLevel = new Set(['inline', 'inline-block', 'ruby', 'ruby-text', 'contents']);

export function displayOfTag(tag: string): string {
	return cssDisplay[tag] ?? 'inline';
}

export function isInlineDisplay(display: string): boolean {
	return inlineLevel.has(display);
}
